name: Deploy to Development

on:
  workflow_run:
    workflows: ["Build and Deploy"]
    types:
      - completed
env:
  GITHUB_ORG: test
  DOCKER_ORG: org-test
  IMG_TAG: ${{ github.sha }}
  IMG_NAME: hkt-user-service
  INFRA_REPO: hkt-infrastructure

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Development
        run: |
          echo ${{ matrix.env.infra_repo }}/kubernetes/${GITHUB_REF#refs/heads/}/deployments/${{ env.IMG_NAME }}
          echo values-${GITHUB_REF#refs/heads/}.yaml values.yaml
          echo "\n\nAppVersion: ${{ env.IMG_TAG }}" >> values.yaml
          echo "Changing Image Version of ${{ env.DOCKER_ORG }}/${{ env.IMG_NAME }}:${{ env.IMG_TAG }}"